### ISSUE TITLE
Video demo

### ISSUE THREAD

**Issue by upintheairsheep** [mad-ady/samygo-debian#2]
Can you make a youtube video demo or screenshots for all of us to enjoy?

**Comment by mad-ady** [comment]
I've stopped using this debian a few years ago. It's currently here more for historical issues.

**Comment by upintheairsheep** [comment]
> I've stopped using this debian a few years ago. It's currently here more for historical issues.

Still have the TV?

**Comment by mad-ady** [comment]
There's not much to showcase. It's just a debian rootfs that gives you
access to all the debian goodies.
I still use the TV, but without its smart parts. I have enough SBCs to run
linux and Android around the house (Odroid devices from Hardkernel), that
are more powerful/versatile than the TV's hardware.
